### ISSUE TITLE
导出-设置导出-应用，没有效果。是我哪弄错了吗

### ISSUE THREAD

**Issue by Pagegle** [alansun2/mapper-generator-javafx#1]
![46@V$~L$ VHQO{_(JNAWI@B](https://user-images.githubusercontent.com/58416574/70982289-b723b800-20f1-11ea-819b-cb43e125d9ad.png)

**Comment by alansun2** [comment]
@Pagegle 看下日志，有报错吗？

**Comment by Pagegle** [comment]
你好，安装目录下app/下没有日志
![图片](https://user-images.githubusercontent.com/58416574/70982857-b3446580-20f2-11ea-8fb3-bfa0bcc09de3.png)

**Comment by Pagegle** [comment]
![44{$%)Q@~B_E B91 _TF0AB](https://user-images.githubusercontent.com/58416574/70982890-c6573580-20f2-11ea-95d4-c47bf4ab67a9.png)

**Comment by alansun2** [comment]
@Pagegle 你尝试换个文件夹试下，前提是这个文件夹是存在的。
这里我没有判断文件夹是否存在，后面我更新下

**Comment by Pagegle** [comment]
@alansun2  好的谢谢
