### ISSUE TITLE
作者不仅还在更新而且还有 Release 版本，真的贴心，点赞

### ISSUE THREAD

**Issue by LeeVicent** [alansun2/mapper-generator-javafx#4]

**Comment by alansun2** [comment]
@LeeVicent 感谢支持，马上又要上一版 release 了！
1. mybaits 支持三种类型的代码生成 （包括无 xml 模式）
2. 支持 tk.mybatis 的生成

**Comment by mioxs** [comment]
我看到此项目依赖 mybatis-extension-plugin 请查看文档更新 https://github.com/mioxs/mybatis-extension-plugin/blob/main/ZH_CN.md
